name: Unit testing and deploy workflow

on:
  workflow_dispatch:
  push:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: SuperPassword

jobs:
  Unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js with version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker-image:
    needs: Unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: knightfury285/solar:${{ github.sha }}

      - name: Test Docker container
        run: |
          docker run --rm -d -p 3000:3000 \
            -e MONGO_URI=${MONGO_URI} \
            -e MONGO_USERNAME=${MONGO_USERNAME} \
            -e MONGO_PASSWORD=${MONGO_PASSWORD} \
            --name solarsystem knightfury285/solar:${{ github.sha }}
          sleep 10
          wget -q -O - http://127.0.0.1:3000/live | grep live
          docker stop solarsystem

  deploy-to-azure-vm:
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy container to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << EOF
            docker pull knightfury285/solar:${{ github.sha }}
            docker stop solarsystem || true
            docker rm solarsystem || true
            docker run -d --name solarsystem -p 3000:3000 \
              -e MONGO_URI=${MONGO_URI} \
              -e MONGO_USERNAME=${MONGO_USERNAME} \
              -e MONGO_PASSWORD=${MONGO_PASSWORD} \
              knightfury285/solar:${{ github.sha }}
          EOF
